// frontend_vue/src/components/BookShelf.vue
<template>
  <div class="bookshelf_main">
    <div class="header">
      <h1>书架页面</h1>
    </div>

    <div class="bookshelf-page">
      <!-- 操作按钮 -->
      <div class="action-buttons">
        <button @click="showForm = 'add'">增加</button>
        <button @click="showForm = 'edit'">更新</button>
        <button @click="showForm = 'delete'">删除</button>
        <button @click="showForm = 'view'">查看</button>
      </div>

      <!-- 条件渲染表单，根据不同的操作显示对应的表单 -->
      <form v-if="showForm" @submit.prevent="handleSubmit">
        <div v-if="showForm === 'add' || showForm === 'edit'">
          <label for="title">书名:</label>
          <input type="text" id="title" v-model="form.title" placeholder="请输入书名" />
          
          <label for="url">链接:</label>
          <input type="text" id="url" v-model="form.url" placeholder="请输入链接" />

          <label for="content">内容:</label>
          <textarea id="content" v-model="form.content" placeholder="请输入内容"></textarea>

          <label for="cover_url">封面链接:</label>
          <input type="text" id="cover_url" v-model="form.cover_url" placeholder="请输入封面链接" />
          <label for="file_path">文件:</label>
          <input type="text" id="file_path" v-model="form.file_path" placeholder="文件" />
        </div>
        <button v-if="showForm === 'add'" type="button" @click="addBook">确认增加</button>
        <button v-if="showForm === 'edit'" type="button" @click="editBook">确认更新</button>
        <button v-if="showForm === 'delete'" type="button" @click="deleteBook">确认删除</button>
        <button v-if="showForm === 'view'" type="button" @click="viewBook">确认查看</button>
      </form>

      <!-- 小说列表展示，点击选择小说 -->
      <ul class="novel-list">
        <li v-for="(novel, index) in paginatedNovels" :key="index" class="novel-item" @click="selectNovel(novel)">
          <img v-if="novel.title" :src="novel.cover_url" alt="封面" class="novel-cover" />
          <div v-if="novel.title" class="novel-info">
            <h2>{{ novel.title }}</h2>
            <p>链接: <a :href="novel.url" target="_blank">{{ novel.url }}</a></p>
          </div>
        </li>
      </ul>

      <!-- 分页 -->
      <div class="pagination">
        <button @click="prevPage" :disabled="currentPage === 1">上一页</button>
        <span>第 {{ currentPage }} 页，共 {{ totalPages }} 页</span>
        <button @click="nextPage" :disabled="currentPage === totalPages">下一页</button>
      </div>
    </div>
  </div>
</template>





<script>
import axios from 'axios';

export default {
  name: 'BookshelfPage',
  data() {
    return {
      form: {
        title: '',
        url: '',
        content: '',
        cover_url: '',
        file_path:''
      },
      novels: [],  // 存储所有小说数据
      currentPage: 1,
      itemsPerPage: 8,
      selectedNovel: null, // 选中的小说对象，用于更新、删除、查看操作
      showForm: null, // 用于控制显示哪个表单
      error: ''
    };
  },
  computed: {
    totalPages() {
      return Math.ceil(this.novels.length / this.itemsPerPage);
    },
    paginatedNovels() {
      const start = (this.currentPage - 1) * this.itemsPerPage;
      const novelsForPage = this.novels.slice(start, start + this.itemsPerPage);

      // 如果当前页的书籍数量不足 8 本，用空对象补齐位置
      while (novelsForPage.length < this.itemsPerPage) {
        novelsForPage.push({}); // 空的书籍对象
      }

      return novelsForPage;
    }
  },
  mounted() {
    this.fetchNovels();
  },
  methods: {
    // 获取所有小说数据
    async fetchNovels() {

      try {
        const response = await axios.get('http://localhost:30600/api/get_all_novels');
        this.novels = response.data;
        console.log('获取到的小说数据:', this.novels);
      } catch (error) {
        console.error("获取小说失败:", error);
      }
    },
    
    // 增加小说，不需要传递小说 ID
    async addBook() {
      console.log('发送的表单数据:', this.form)
      try {
        const response = await axios.post('http://localhost:30600/api/add_novel', this.form);
        alert('小说添加成功');
        this.fetchNovels(); // 添加成功后刷新小说列表
        this.resetForm(); // 重置表单
      } catch (error) {
        this.error = error.message;
      }
    },

    // 更新小说，需要传递小说 ID
    async editBook() {
      if (!this.selectedNovel) {
        alert('请先选择要更新的小说');
        return;
      }
      try {
        const response = await axios.put(`http://localhost:30600/api/update_novel/${this.selectedNovel.id}`, this.form);
        alert('小说更新成功');
        this.fetchNovels(); // 更新成功后刷新小说列表
        this.resetForm(); // 重置表单
      } catch (error) {
        this.error = error.message;
      }
    },

    // 删除小说，需要传递小说 ID
    async deleteBook() {
      if (!this.selectedNovel) {
        alert('请先选择要删除的小说');
        return;
      }
      try {
        await axios.delete(`http://localhost:30600/api/delete_novel/${this.selectedNovel.id}`);
        alert('小说删除成功');
        this.fetchNovels(); // 删除成功后刷新小说列表
        this.resetForm(); // 重置表单
      } catch (error) {
        this.error = error.message;
      }
    },

    // 查看单个小说信息
    async viewBook() {
      if (!this.selectedNovel) {
        alert('请先选择要查看的小说');
        return;
      }
      try {
        const response = await axios.get(`http://localhost:30600/api/get_novel/${this.selectedNovel.id}`);
        this.form = response.data; // 将获取到的小说信息填充到表单中
      } catch (error) {
        this.error = error.message;
      }
    },
    
    // 选择小说
    selectNovel(novel) {
      this.selectedNovel = novel;
      this.form = { ...novel }; // 选中小说后，将小说详情填充到表单中
    },

    // 翻页方法
    nextPage() {
      if (this.currentPage < this.totalPages) {
        this.currentPage++;
      }
    },
    prevPage() {
      if (this.currentPage > 1) {
        this.currentPage--;
      }
    },

    // 重置表单
    resetForm() {
      this.form = {
        title: '',
        url: '',
        content: '',
        cover_url: '',
        file_path: ''
      };
      this.selectedNovel = null;
      this.showForm = null;
    }
  }
};
</script>



<style scoped>
.bookshelf-page {
  width: 100%;
  margin: 0 auto;
  padding: 20px;
  background-color: #f4f6f9;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  border-radius: 10px;
}

.header {
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
}

h1 {
  text-align: center;
  color: #2c3e50;
  font-family: 'Helvetica Neue', Arial, sans-serif;
  margin-bottom: 40px;
}

.novel-list {
  display: grid;
  grid-template-columns: repeat(4, 1fr); /* 一排四本书 */
  gap: 20px;
  list-style-type: none;
  padding: 0;
  justify-content: center;
}

.novel-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 15px;
  background-color: #ffffff;
  border-radius: 12px;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.05);
  transition: transform 0.3s ease, box-shadow 0.3s ease;
  min-height: 250px; /* 设置最小高度，确保空白也占位置 */
}

.novel-item:hover {
  transform: translateY(-5px);
  box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);
}

.novel-cover {
  width: 120px;
  height: 180px;
  object-fit: cover;
  margin-bottom: 15px;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.novel-info {
  text-align: center;
}

.novel-info h2 {
  margin: 10px 0;
  font-size: 18px;
  color: #34495e;
}

.novel-info a {
  color: #3498db;
  text-decoration: none;
}

.novel-info a:hover {
  text-decoration: underline;
}

/* 分页按钮样式 */
.pagination {
  display: flex;
  justify-content: center;
  margin-top: 20px;
}

.pagination button {
  background-color: #3498db;
  color: white;
  border: none;
  padding: 10px 15px;
  margin: 0 10px;
  cursor: pointer;
  border-radius: 5px;
  transition: background-color 0.3s;
}

.pagination button:disabled {
  background-color: #95a5a6;
  cursor: not-allowed;
}

.pagination span {
  line-height: 36px;
}

.action-buttons {
  right: 80px; /* 调整位置 */
  top: 10px; /* 调整位置 */
  gap: 10px;
}

.action-buttons button {
  background-color: #3498db;
  color: white;
  border: none;
  padding: 8px 12px;
  border-radius: 5px;
  cursor: pointer;
  transition: background-color 0.3s;
}

.action-buttons button:hover {
  background-color: #2980b9;
}

.bookshelf_main{
  width: 80%;
}

</style>

// frontend_recat/src/components/bookshelf.jsx
import "../css/bookshelf.css";
import React, { useState, useEffect } from 'react';
import axios from 'axios';


const Bookshelf = () => {
  const [form, setForm] = useState({
    title: '',
    url: '',
    content: '',
    cover_url: '',
    file_path: '',
  });
  const [novels, setNovels] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 8;
  const [selectedNovel, setSelectedNovel] = useState(null);
  const [showForm, setShowForm] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    fetchNovels();
  }, []);

  const fetchNovels = async () => {
    try {
      const response = await axios.get('http://localhost:30600/api/get_all_novels');
      setNovels(response.data);
    } catch (error) {
      console.error('Failed to fetch novels:', error);
    }
  };

  const totalPages = Math.ceil(novels.length / itemsPerPage);
  const paginatedNovels = novels.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);

  const handleInputChange = (e) => {
    const { id, value } = e.target;
    setForm((prev) => ({ ...prev, [id]: value }));
  };

  const resetForm = () => {
    setForm({
      title: '',
      url: '',
      content: '',
      cover_url: '',
      file_path: '',
    });
    setSelectedNovel(null);
    setShowForm(null);
  };

  const addBook = async () => {
    try {
      await axios.post('http://localhost:30600/api/add_novel', form);
      alert('Book added successfully!');
      fetchNovels();
      resetForm();
    } catch (error) {
      setError(error.message);
    }
  };

  const editBook = async () => {
    if (!selectedNovel) {
      alert('Please select a book to edit');
      return;
    }
    try {
      await axios.put(`http://localhost:30600/api/update_novel/${selectedNovel.id}`, form);
      alert('Book updated successfully!');
      fetchNovels();
      resetForm();
    } catch (error) {
      setError(error.message);
    }
  };

  const deleteBook = async () => {
    if (!selectedNovel) {
      alert('Please select a book to delete');
      return;
    }
    try {
      await axios.delete(`http://localhost:30600/api/delete_novel/${selectedNovel.id}`);
      alert('Book deleted successfully!');
      fetchNovels();
      resetForm();
    } catch (error) {
      setError(error.message);
    }
  };

  const viewBook = async () => {
    if (!selectedNovel) {
      alert('Please select a book to view');
      return;
    }
    try {
      const response = await axios.get(`http://localhost:30600/api/get_novel/${selectedNovel.id}`);
      setForm(response.data);
    } catch (error) {
      setError(error.message);
    }
  };

  const selectNovel = (novel) => {
    setSelectedNovel(novel);
    setForm(novel);
  };

  return (
    <div className="bookshelf_main">
      <div className="header">
        <h1>Bookshelf Page</h1>
      </div>
      <div className="bookshelf-page">
        <div className="action-buttons">
          <button onClick={() => setShowForm('add')}>增加小说</button>
          <button onClick={() => setShowForm('edit')}>更新小说</button>
          <button onClick={() => setShowForm('delete')}>删除小说</button>
          <button onClick={() => setShowForm('view')}>View</button>
        </div>

        {showForm && (
          <form onSubmit={(e) => e.preventDefault()}>
            {(showForm === 'add' || showForm === 'edit') && (
              <>
                <label htmlFor="title">Title:</label>
                <input type="text" id="title" value={form.title} onChange={handleInputChange} />

                <label htmlFor="url">URL:</label>
                <input type="text" id="url" value={form.url} onChange={handleInputChange} />

                <label htmlFor="content">Content:</label>
                <textarea id="content" value={form.content} onChange={handleInputChange}></textarea>

                <label htmlFor="cover_url">Cover URL:</label>
                <input type="text" id="cover_url" value={form.cover_url} onChange={handleInputChange} />

                <label htmlFor="file_path">File Path:</label>
                <input type="text" id="file_path" value={form.file_path} onChange={handleInputChange} />
              </>
            )}

            {showForm === 'add' && <button onClick={addBook}>Add Book</button>}
            {showForm === 'edit' && <button onClick={editBook}>Edit Book</button>}
            {showForm === 'delete' && <button onClick={deleteBook}>Delete Book</button>}
            {showForm === 'view' && <button onClick={viewBook}>View Book</button>}
          </form>
        )}

        <ul className="novel-list">
          {paginatedNovels.map((novel, index) => (
            <li key={index} className="novel-item" onClick={() => selectNovel(novel)}>
              {novel.title && (
                <>
                  <img src={novel.cover_url} alt="Cover" class="novel-cover"/>
                  <div>
                    <h2>{novel.title}</h2>
                    <p>
                      URL: <a href={novel.url}>{novel.url}</a>
                    </p>
                  </div>
                </>
              )}
            </li>
          ))}
        </ul>

        <div className="pagination">
          <button onClick={() => setCurrentPage((p) => Math.max(p - 1, 1))} disabled={currentPage === 1}>
            Previous
          </button>
          <span>
            Page {currentPage} of {totalPages}
          </span>
          <button onClick={() => setCurrentPage((p) => Math.min(p + 1, totalPages))} disabled={currentPage === totalPages}>
            Next
          </button>
        </div>
      </div>
    </div>
  );
};

export default Bookshelf;
